
name: Auto Comment on Issues and PRs
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post a default comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHCRPASS }}
          script: |
            const issue_number = context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: `### Default Comment Template
              - **Describe the issue or change:**
              - **Steps to reproduce:**
              - **Expected behavior:**
              - **Additional information:**`
            });
