
name: GHCR - Install SD-Core 5G

on:
  workflow_dispatch:


jobs:
  install:
    runs-on: ubuntu-latest  # Using our own self hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


 # Step 2: Set up Docker authentication for GHCR securely
      - name: Set up Docker authentication for GHCR
        run: |
          docker login ghcr.io -u "${{ secrets.GHCRUSER }}" --password-stdin <<< "${{ secrets.GHCRPASS }}"

 
        
      - name: Install SD-Core
        run: |
          make aether-5gc-install  # Running from repo home
          kubectl get pods -n omec

      - name: Install Management Application
        run: |
          make aether-amp-install  # Running from repo home
